"""Corrigindo estrutura da tabela Pedido

Revision ID: 55ebe31f55fb
Revises: e25f99bdb940
Create Date: 2025-02-24 08:33:20.764492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ebe31f55fb'
down_revision = 'e25f99bdb940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requisicao_id', sa.Integer(), nullable=False))

        # 🔹 Removendo constraint com nome explícito (caso exista uma antiga)
        conn = op.get_bind()  # Conexão com o banco de dados
        insp = sa.inspect(conn)  # Inspeciona a estrutura do banco

# Verifica se a constraint existe antes de tentar remover
        existing_constraints = [fk['name'] for fk in insp.get_foreign_keys('pedido')]

        if 'fk_pedido_requisitante' in existing_constraints:
            with op.batch_alter_table('pedido', schema=None) as batch_op:
                batch_op.drop_constraint('fk_pedido_requisitante', type_='foreignkey')



        # 🔹 Criando a nova chave estrangeira com um nome válido
        batch_op.create_foreign_key('fk_pedido_requisicao', 'requisicao', ['requisicao_id'], ['id'])

        # 🔹 Removendo a coluna antiga
        batch_op.drop_column('requisitante_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requisitante_id', sa.Integer(), nullable=False))

        # 🔹 Removendo a foreign key errada
        batch_op.drop_constraint('fk_pedido_requisicao', type_='foreignkey', if_exists=True)

        # 🔹 Restaurando a foreign key antiga, se necessário
        batch_op.create_foreign_key('fk_pedido_requisitante', 'user', ['requisitante_id'], ['id'])

        # 🔹 Removendo a nova coluna requisicao_id caso precise reverter
        batch_op.drop_column('requisicao_id')

    # ### end Alembic commands ###
