"""Adiciona campo aprovada em NotaFiscal

Revision ID: eeddccfcf3e1
Revises: 33b1934c594a
Create Date: 2025-02-26 11:09:46.382096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeddccfcf3e1'
down_revision = '33b1934c594a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aprovada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.drop_column('aprovada')

    # ### end Alembic commands ###
